### ISSUE TITLE
Move client away from bravado

### ISSUE THREAD

**Issue by david4096** [common-workflow-language/workflow-service#20]
For your consideration: bravado has no plans to support OpenAPI 3.

https://github.com/Yelp/bravado/issues/306

We should consider alternatives.

**Comment by advance512** [comment]
What did you end up doing?

**Comment by tetron** [comment]
Since the API is simple, we replaced it with a handwritten client using `requests`, although we haven't migrated the schema to OpenAPI 3 yet.
