### ISSUE TITLE
Install using pip fails

### ISSUE THREAD

**Issue by dpfoose** [common-workflow-language/workflow-service#4]
On both python 2.7 and python 3.5, in virtualenvs, installing via `pip install wes-service` fails:
```
Collecting wes-service
  Downloading wes-service-2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-61IIFM/wes-service/setup.py", line 16, in <module>
        long_description=open(README).read(),
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-61IIFM/wes-service/README.md'
```
pip and setuptools were both upgraded using `pip install --upgrade` before running `pip install wes-service`

Running `python setup.py install` successfully installs the package.

**Comment by david4096** [comment]
Yeah, I noticed the same and installed using

`pip install git+git://github.com/common-workflow-language/workflow-service`

for now!

**Comment by david4096** [comment]
Fixed this in a future version by adding the pypi readme to the repository.

This can be maintained by converting from the markdown `pandoc -t rst README.md > README.pypi.rst`
