### ISSUE TITLE
Implement/test workflow_attachments

### ISSUE THREAD

**Issue by david4096** [common-workflow-language/workflow-service#41]
The multipart upload feature enables uploading multiple attachments to stage a workflow as suggested in the schemas: https://github.com/ga4gh/workflow-execution-service-schemas/blob/develop/openapi/workflow_execution_service.swagger.yaml#L123

To properly demonstrate this, the workflow run endpoint should check for the presence of a workflow attachments form upload. The filename of this should be checked following the suggestion in the schemas so that malicious rewrites aren't easy. The presence of these files should be guaranteed in a new test, which uploads a local tool description in addition to the workflow descriptor.

**Comment by david4096** [comment]
@tetron I believe this can be closed?

**Comment by tetron** [comment]
Sounds good to me.
